<?php

namespace CAF\ContentBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;


/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryTranslationRepository extends EntityRepository
{

	public function getCategoryLang($lang) {
		return $this->getEntityManager()
					->createQueryBuilder('ct')
                    ->Select('ct')
                    ->from('CAFContentBundle:CategoryTranslation','ct')
                    ->where('ct.lang=:lang')
                    ->setParameter('lang', $lang)
                    ->andwhere('ct.published=:published')
                    ->setParameter('published',1)
        ;            
	}

    public function findByUrl($url)
    {
        return $this->getEntityManager()
                        ->createQueryBuilder('ct')
                        ->Select('ct')
                        ->from('CAFContentBundle:CategoryTranslation', 'ct')
                        ->where('ct.url=:url')
                        ->setParameter('url', $url)
                        ->getQuery()
                        ->getResult();
    }
}