<?php

namespace CAF\ContentBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentTranslationRepository extends EntityRepository
{

	public function findByUrl($url)
	{
		return $this->getEntityManager()
						->createQueryBuilder('ct,fv')
						->Select('ct,fv')
						->from('CAFContentBundle:ContentTranslation', 'ct')
						->join('ct.fieldsvalue', 'fv')
						->join('fv.field','f')
						->join('ct.content_urls','cu')
						->where('cu.url=:url')
						->setParameter('url', $url)
						->getQuery()
						->getResult();
	}
}