<?php

namespace CAF\ContentBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldsValueRepository extends EntityRepository
{

	public function getValues($id_translation)
	{
		$results = $this->getEntityManager()
					->createQueryBuilder('fv,f')
					->Select('fv,f')
					->from('CAFContentBundle:FieldsValue','fv')
					->join('fv.field','f')
					->where('fv.content_translation=:id')
					->setParameter('id',$id_translation)
					->getQuery()
					->getResult();
		return $results;			
	}
}