<?php

namespace CAF\ContentBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetasValueCategoryRepository extends EntityRepository
{

	public function getValues($id_translation)
	{
		$results = $this->getEntityManager()
					->createQueryBuilder('mv,m')
					->Select('mv,m')
					->from('CAFContentBundle:MetasValueCategory','mv')
					->join('mv.meta','m')
					->where('mv.category_translation=:id')
					->setParameter('id',$id_translation)
					->getQuery()
					->getResult();
		return $results;			
	}
}