<?php

namespace CAF\ContentBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UrlsContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlsContentRepository extends EntityRepository
{
	public function getUrlByContentTranslation($id) {
		return $this->getEntityManager()
					->createQueryBuilder('u.url')
					->Select('u.url')
					->from('CAFContentBundle:UrlsContent','u')
					->leftjoin('u.content_translation','ct')
					->where('ct.id=:id')
					->setParameter('id',$id)
					->getQuery()
					->getSingleResult();
	}
}
