<?php

namespace CAF\FormBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulaireRepository extends EntityRepository
{

    public function getPagination($nb_elem_page) {
    	$nb_elem = $this->getEntityManager()
					->createQueryBuilder('c')
					->Select('count(c)')
					->from('CAFFormBundle:Formulaire','c')
					->getQuery()
					->getSingleResult();
    	$nb_elem = current($nb_elem);
        $nb_elem_page = $nb_elem_page*3;
    	return ceil($nb_elem/$nb_elem_page);
    }

    
    public function findAllOrder($page,$nb_elem = 20,$taxonomy = -1)
    {   
        
        $offset = ($page-1)*$nb_elem;
        if($offset < 0)
            $offset=0;
        $offset = $offset*3;
        if($nb_elem==-1)
            $nb_elem=20;
        $max = $nb_elem*3;
        if ($taxonomy == -1) {
            return $this->getEntityManager()
                ->createQueryBuilder('c')
                ->Select('c')
                ->from('CAFFormBundle:Formulaire','c')
               // ->leftjoin('c.translations', 't')
                //->orderby('t.created', 'DESC')
                ->setFirstResult($offset)
                ->setMaxResults($max)
                ->getQuery()
                ->getResult();  
        } else {
            return $this->getEntityManager()
                ->createQueryBuilder('c')
                ->Select('c')
                ->from('CAFFormBundle:Formulaire','c')
                //->leftjoin('c.translations', 't')
                ->leftjoin('c.id_form_taxonomy', 'ct')
                ->where('ct.id=:taxonomy')
               // ->orderby('t.created', 'DESC')
                ->setParameter('taxonomy',$taxonomy)
                ->setFirstResult($offset)
                ->setMaxResults($max)
                ->getQuery()
                ->getResult();
        }
        
    }
}